### ISSUE TITLE
Test fails in chrrot enviroments

### ISSUE THREAD

**Issue by werdahias** [zeenix/xdg-home#16]
In debian we build all packages in chroot enviroments. Naturally, this has no /home set. This leads to the following test error:

```
running 1 test
test tests::home ... FAILED

failures:

---- tests::home stdout ----
thread 'tests::home' panicked at src/lib.rs:114:13:
assertion `left == right` failed
  left: "/var/lib/sbuild"
 right: "/<<PKGBUILDDIR>>/fakehome"
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:408:17
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:363:5
   4: xdg_home::tests::home
             at /usr/share/cargo/registry/xdg-home-1.3.0/src/lib.rs:114:13
   5: xdg_home::tests::home::{{closure}}
             at /usr/share/cargo/registry/xdg-home-1.3.0/src/lib.rs:103:14
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::home

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

Maybe a check makes sense here if /home does not exist ?

**Comment by zeenix** [comment]
> Maybe a check makes sense here if /home does not exist ?

Maybe. Could you please provide a PR for this?
